//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabinets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cabinets()
        {
            this.Items = new HashSet<Items>();
            this.WrittenOffItems = new HashSet<WrittenOffItems>();
        }
    
        public int Id_Cabinets { get; set; }
        public string Cabinet { get; set; }
        public Nullable<int> EducBuild_Id { get; set; }
    
        public virtual EducBuilds EducBuilds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Items> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WrittenOffItems> WrittenOffItems { get; set; }
    }
}
