//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UHV_DBEntities6 : DbContext
    {
        public UHV_DBEntities6()
            : base("name=UHV_DBEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinets> Cabinets { get; set; }
        public virtual DbSet<EducBuilds> EducBuilds { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<WrittenOffItems> WrittenOffItems { get; set; }
    }
}
