//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int Id_Items { get; set; }
        public string InvNumb { get; set; }
        public string ItemName { get; set; }
        public string NomenkNumb { get; set; }
        public int ItemNumb { get; set; }
        public decimal ItemPrice { get; set; }
        public int ItemYear { get; set; }
        public System.DateTime ItemArrDate { get; set; }
        public int Cabinets_Id { get; set; }
    
        public virtual Cabinets Cabinets { get; set; }
    }
}
