//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UHV
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrittenOffItems
    {
        public int Id { get; set; }
        public string InvNumb { get; set; }
        public string ItemName { get; set; }
        public string NomenkNumb { get; set; }
        public Nullable<int> ItemNumb { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public Nullable<int> ItemYear { get; set; }
        public Nullable<System.DateTime> ItemArrDate { get; set; }
        public Nullable<int> WrittenCabinet_Id { get; set; }
        public string WrittReason { get; set; }
    
        public virtual Cabinets Cabinets { get; set; }
    }
}
